models/UserLog.php
<?php

namespace app\models;


use app\models\behaviors\TimestampBehavior;

/**
 * Class UserLog
 * @package app\models
 *
 * @property $id
 * @property $user_id
 * @property $ip
 * @property $controller
 * @property $action
 * @property $method
 * @property $message
 * @property $browser_finger
 * @property $created_at
 */
class UserLog extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user_log}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at']
                ]
            ]
        ];
    }

    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public static function add($action, $message = null)
    {
        $app = \Yii::$app;
        if (!$app->request->getIsPjax()) {
            $controller = $action->controller->id;
            $user_id = $app->user->getId();
            $new = new self();
            $new->user_id = $user_id;
            $new->ip = $app->request->remoteIP;
            $new->browser_finger = $app->request->getUserAgent();
            $new->controller = $controller;
            $new->action = $action->id;
            $new->method = $app->request->getMethod();
            $new->message = $message ?? json_encode([$app->request->get(), $app->request->post()]) ?? null;

            if ($last_record = self::find()->orderBy('id DESC')->one()) {
                if ($last_record->action != $action->id | $last_record->user_id != $user_id) {
                    $new->save();
                }
            } else {
                $new->save();
            }
        }
    }
}

controllers/UserLogController.php
<?php

namespace app\controllers;

use app\models\search\UserLogSearch;
use app\models\UserLog;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use app\components\AuthUser;

/**
 * Class AutogotoifCustomController
 * @package app\controllers
 */
class UserLogController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'view','delete'],
                        'allow' => true,
                        'roles' => ['root'],
                    ]
                ]
            ],
        ];
    }

    /**
     * @return string
     * @throws ForbiddenHttpException
     */
    public function actionIndex()
    {
        $searchModel = new UserLogSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $statistics = $searchModel->searchStatistic();

        $date = [];
        $pageACount = [];
        $pageBCount = [];
        $buyCowCount = [];
        $downloadCount = [];
        if($statistics){
            foreach ($statistics as $statistic){
                $date[]=explode(' ',$statistic['date'])[0];
                $pageACount[]=$statistic['count_page_a'];
                $pageBCount[]=$statistic['count_page_b'];
                $buyCowCount[]=$statistic['count_buy_cow'];
                $downloadCount[]=$statistic['count_download_exe'];
            }
        }
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'date'=>json_encode($date),
            'pageACount'=>json_encode($pageACount),
            'pageBCount'=>json_encode($pageBCount),
            'buyCowCount'=>json_encode($buyCowCount),
            'downloadCount'=>json_encode($downloadCount),
        ]);
    }

    /**
     * @param $id
     * @return string
     * @throws ForbiddenHttpException
     * @throws NotFoundHttpException
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * @param $id
     * @return UserLog|array|\yii\db\ActiveRecord|null
     * @throws ForbiddenHttpException
     * @throws NotFoundHttpException
     */
    protected function findModel($id)
    {
        if (($model = UserLog::find()->where(['id' => $id])->one()) !== null) {

            if (AuthUser::userCan('root')) {
                return $model;
            }
            

            throw new ForbiddenHttpException('Permission denied');
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/user-log/_user_log.php
<?php

use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use kartik\daterange\DateRangePicker;

/* @var $dataProvider app\controllers\UserLogController */
/* @var $searchModel app\controllers\UserLogController */

?>
<?php Pjax::begin(); ?>
<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'columns' => [
        [
            'label' => 'User',
            'attribute' => 'user_id',
            'format' => 'raw',
            'filter' => Html::activeDropDownList(
                $searchModel,
                'user_id',
                ArrayHelper::map(\app\models\User::find()->all(), 'id', 'username'),
                ['class' => 'form-control', 'prompt' => 'All users']
            ),
            'value' => function ($model) {
                $tooltip = " data-toggle='tooltip' data-placement='top' title='{$model->browser_finger}' ";
                return "<span $tooltip>" . ($model->user->username ?? '-') . "</span>";
            }
        ],

        [
            'attribute' => 'ip',
            'format' => 'raw',
            'value' => function ($model) {
                $tooltip = " data-toggle='tooltip' data-placement='top' title='{$model->browser_finger}' ";
                return "<span $tooltip>" . ($model->ip) . "</span>";
            }
        ],
        [
            'attribute' => 'controller',
            'filter' => Html::activeDropDownList(
                $searchModel,
                'controller',
                ArrayHelper::map(\app\models\UserLog::find()->select('DISTINCT(controller)')->asArray()->cache(100)->all(), 'controller', 'controller'),
                ['class' => 'form-control', 'prompt' => '---']
            ),
        ],
        [
            'attribute' => 'action',
            'filter' => Html::activeDropDownList(
                $searchModel,
                'action',
                ArrayHelper::map(\app\models\UserLog::find()->select('DISTINCT(action)')->asArray()->cache(100)->all(), 'action', 'action'),
                ['class' => 'form-control', 'prompt' => '---']
            ),
        ],
        [
            'attribute' => 'method',
            'filter' => Html::activeDropDownList(
                $searchModel,
                'method',
                ArrayHelper::map(\app\models\UserLog::find()->select('DISTINCT(method)')->asArray()->cache(100)->all(), 'method', 'method'),
                ['class' => 'form-control', 'prompt' => '---']
            ),
        ],
        [
            'attribute' => 'message',
            'format' => 'raw',
            'value' => function ($model) {
                return is_array(json_decode($model->message)) ? (json_encode(json_decode($model->message)[0] ?? '')) : $model->message;
            }
        ],
        [
            'filter' => DateRangePicker::widget([
                'model' => $searchModel,
                'attribute' => 'data_time',
                'convertFormat' => true,
                'options' => [
                    'class' => 'form-control',
                    'placeholder' => date("Y-m-d H:i") . ' - ' . date("Y-m-d H:i"),
                    //'readonly' => true,
                ],
                'pluginOptions' => [
                    'showDropdowns' => true,
                    'autoApply' => true,
                    'buttonClasses' => 'hidden',
                    'timePicker' => true,
                    'timePicker24Hour' => true,
                    'timePickerSeconds' => true,
                    'locale' => [
                        'format' => 'Y-m-d H:i:s',
                    ],
                    'ranges' => [
                        Yii::t('kvdrp', "Today") => ["moment().startOf('day')", "moment().endOf('day')"],
                        Yii::t('kvdrp', "Yesterday") => ["moment().startOf('day').subtract(1,'days')", "moment().endOf('day').subtract(1,'days')"],
                        Yii::t('kvdrp', "Last {n} Days", ['n' => 7]) => ["moment().startOf('day').subtract(6, 'days')", "moment().endOf('day')"],
                        Yii::t('kvdrp', "Last {n} Days", ['n' => 30]) => ["moment().startOf('day').subtract(29, 'days')", "moment().endOf('day')"],
                        Yii::t('kvdrp', "This Month") => ["moment().startOf('month')", "moment().endOf('month')"],
                        Yii::t('kvdrp', "Last Month") => ["moment().subtract(1, 'month').startOf('month')", "moment().subtract(1, 'month').endOf('month')"],

                    ]
                ],
            ]),
            'attribute' => 'created_at',
            'format' => 'datetime',
        ],
        [
            'format' => 'raw',
            'visible' => \app\components\AuthUser::userCan('debug'),
            'value' => function ($model) {
                return Html::a('Детально', ['user-log/view', 'id' => $model->id]);
            }
        ]
    ],
]); ?>
<?php Pjax::end(); ?>

views/user-log/_user_statistic.php
<?php

/* @var $date app\controllers\UserLogController */
/* @var $pageACount app\controllers\UserLogController */
/* @var $pageBCount app\controllers\UserLogController */
/* @var $buyCowCount app\controllers\UserLogController */
/* @var $downloadCount app\controllers\UserLogController */
?>

<div>
    <figure class="highcharts-figure">
        <div id="container"></div>
    </figure>

</div>
<?php $this->registerJs("
     Highcharts.chart('container', {
        chart: {
            zoomType: 'xy'
        },
        title: {
            text: 'User activity statistics',
            align: 'left'
        },
        xAxis: [{
            categories: {$date},
            crosshair: true
        }],
        yAxis: [{ 
            labels: {
                format: '{value} ',
                style: {
                    color: Highcharts.getOptions().colors[0]
                }
            },
            title: {
                text: 'Page A',
                style: {
                    color: Highcharts.getOptions().colors[0]
                }
            }
        }, { 
            title: {
                text: 'Page B',
                style: {
                    color: Highcharts.getOptions().colors[1]
                }
            },
            labels: {
                format: '{value} ',
                style: {
                    color: Highcharts.getOptions().colors[1]
                }
            },
            opposite: true
        }],
        tooltip: {
            shared: true
        },
        legend: {
            align: 'left',
            x: 80,
            verticalAlign: 'top',
            y: 80,
            floating: true,
            backgroundColor:
                Highcharts.defaultOptions.legend.backgroundColor || // theme
                'rgba(255,255,255,0.25)'
        },
        series: [{
            name: 'Page A',
            type: 'column',
            yAxis: 1,
            data: {$pageACount},
            tooltip: {
                valueSuffix: ' times'
            }

        }, 
         {
            name: 'Page B',
            type: 'column',
            data: {$pageBCount},
            tooltip: {
                valueSuffix: ' times'
            }
        },
        {
            name: 'Buy Cow',
            type: 'column',
            data: {$buyCowCount},
            tooltip: {
                valueSuffix: ' times'
            }
        }, 
         {
            name: 'Download',
            type: 'column',
            data: {$downloadCount},
            tooltip: {
                valueSuffix: ' times'
            }
        }
        ]
    });
") ?>

views/user-log/index.php
<?php

use yii\bootstrap4\Tabs;
use yii\helpers\Html;

/* @var $dataProvider app\controllers\UserLogController */
/* @var $searchModel app\controllers\UserLogController */
/* @var $date app\controllers\UserLogController */
/* @var $pageACount app\controllers\UserLogController */
/* @var $pageBCount app\controllers\UserLogController */
/* @var $buyCowCount app\controllers\UserLogController */
/* @var $downloadCount app\controllers\UserLogController */


$this->title = 'UserLog';
$this->params['breadcrumbs'][] = $this->title;
?>
<h1><?= Html::encode($this->title) ?></h1>

<div>
    <?php echo Tabs::widget([
        'encodeLabels' => false,
        'items' => [
            [
                'label' => "User Log",
                'content' => $this->render('_user_log', compact('dataProvider', 'searchModel')),
                'active' => true,
            ],
            [
                'label' => "Statistics",
                'content' => $this->render('_user_statistic', compact('date', 'pageACount',
                    'pageBCount', 'buyCowCount', 'downloadCount')),
            ],
        ],
    ]); ?>
</div>

views/user-log/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use app\components\AuthUser;

/* @var $this yii\web\View */
/* @var $model \app\models\UserLog */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Logs', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="dialplan-view">

    <?= DetailView::widget([
        'model' => $model,
    ]) ?>


</div>