controllers/AuthController.php
<?php

namespace app\controllers;


use app\components\AuthUser;
use app\models\forms\SignupForm;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use app\models\forms\LoginForm;

/**
 *
 */
class AuthController extends Controller
{
    /**
     * @return array[]
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'sign-up'],
                        'allow' => true,
                        'roles' => ['?']
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ],
            ],

        ];
    }
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        $layout = AuthUser::isAuth()?'@app/views/layouts/main.php':'@app/views/layouts/auth.php';
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
                'layout' => $layout
            ]
        ];
    }
    /**
     * @return string|Response
     */
    public function actionSignUp()
    {

        $this->layout = '@app/views/layouts/auth.php';

        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post()) && $model->signup()) {
            return $this->redirect(['site/index']);
        }

        $model->password = '';
        return $this->render('signup', [
            'model' => $model,
        ]);
    }
    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        $this->layout = '@app/views/layouts/auth.php';

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(['site/index']);
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }
    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->redirect(['auth/login']);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\UserLog;
use app\rbac\Rbac;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use app\components\AuthUser;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => [ 'index','page-a','page-b','buy-cow','download-exe'],
                        'allow' => true,
                        'roles' => ['@']
                    ],
                    [
                        'actions' => [ 'error'],
                        'allow' => true,
                    ]
                ]
            ]
        ];
    }
    /**
     * @param $action
     * @return bool
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action): bool
    {
        UserLog::add($action);
        return parent::beforeAction($action);
    }

    /**
     * @return string|Response
     */
    public function actionIndex()
    {
        if (AuthUser::userCan(Rbac::ROLE_ROOT)) {
            return $this->redirect(['user-log/index']);
        }
      return $this->render('index');
    }
    /**
     * @return string
     */
    public function actionPageA()
    {
          return $this->render('page-a');
    }

    /**
     * @return string
     */
    public function actionPageB()
    {
      return $this->render('page-b');
    }
    /**
     * @return Response
     */
    public function actionBuyCow()
    {
        Yii::$app->session->set('buy-cow',true);
        Yii::$app->session->setFlash('success', 'thankYou' );
        return $this->redirect(['site/index']);
    }
    /**
     * @return Response
     */
    public function actionDownloadExe()
    {
        $path = glob(Yii::getAlias('@app/runtime/test.exe'));
        return Yii::$app->response->sendFile($path[0]);
    }

}

views/layouts/auth.php
<?php

/* @var $this \yii\web\View */

/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use app\assets\AuthAsset;

AuthAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <link rel="icon" href="<?=getenv('ALT_LOGO_LOGIN')??'/favicon.png'?>" sizes="32x32">
    <style>
        body {
            height: 100%;
            background-color: #ebf2f2 !important;
            font-family: 'Roboto', sans-serif;
            font-weight: 300;
            color: #363636;
        }
        .login-container {
            box-shadow: 0 0 33px 0px #0000003b;
            background: white;
            border-radius: 5px;
            border: 1px solid #ceccccc7;
            margin-top: 50px;
        }
        .form-group{
            margin-bottom: 0!important;
        }
        .logo{
            margin-top: 50px;
        }
    </style>
</head>
<?php if(getenv('ALT_LOGIN_BACKGROUND_IMG')){ ?>
<body style="background-image: url('<?=getenv('ALT_LOGIN_BACKGROUND_IMG')?>'); background-position: center;background-size: cover; ">
<?php }else{ ?>
<body>
<?php } ?>

<?php $this->beginBody() ?>

<div class="wrap">

    <div class="container">
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */

/* @var $content string */

use app\components\AddVarJs;
use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use app\components\AuthUser;
use app\rbac\Rbac;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?php $this->registerCsrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
        <link rel="icon"
              href="<?= getenv('ALT_FAVICON') ? getenv('ALT_FAVICON') : (getenv('ALT_LOGO') ? getenv('ALT_LOGO') : '/favicon.png') ?>"
              sizes="32x32">
    </head>
    <body>
    <?php $this->beginBody() ?>

    <div class="wrap">

        <?php
        NavBar::begin([
            'brandLabel' => Yii::$app->name,
            'brandUrl' => '/',
            'id' => 'main-navbar',
            'brandImage' => '',
            'options' => [
                    'style'=>'max-height: 25px',
                'class' => 'navbar navbar-expand-lg fixed-left navbar-light bg-light',
            ]
        ]);

        $items[] = [
            'label' => 'Main',
            'url' => ['/site/index'],
        ];
        $items[] = [
            'label' => 'Page A',
            'url' => ['/site/page-a'],
        ];
        $items[] = [
            'label' => 'Page B',
            'url' => ['/site/page-b'],
        ];

        $items[] = [
            'label' => '<i class="fas fa-user red"></i> User Statistic',
            'url' => ['/user-log/index'],
            'visible' => AuthUser::userCan(Rbac::ROLE_ROOT)
        ];


        $username = AuthUser::getUser()->username;
        $items[] = "<li><a>{$username}</a></li>";

        $items[] = [
            'label' => '<i class="fas fa-sign-out-alt"></i> ',
            'url' => ['/auth/logout'],
        ];

        echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-right'],
            'items' => $items,
            'id' => 'main-navbar-ty',
            'encodeLabels' => false
        ]);
        NavBar::end();
        ?>


        <div class="container-fluid">
            <?= Breadcrumbs::widget([
                'homeLink' => [
                    'label' => '#',
                    'url' => ['/'],
                ],
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]) ?>
            <?= Alert::widget() ?>
            <?= $content ?>
        </div>
    </div>

    <?php $this->endBody() ?>

    <footer class="bg-light text-center text-lg-start fixed-bottom">
        <!-- Copyright -->
        <div class="text-center p-3 text-muted">
            © <?= date('Y'); ?> <?= getenv('APP_NAME') ?>
            <a class="text-dark" href="/">Alpha 0.1</a>
        </div>
        <!-- Copyright -->
    </footer>

    </body>

    </html>
<?php $this->endPage() ?>