controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\UserLog;
use app\rbac\Rbac;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use app\components\AuthUser;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => [ 'index','page-a','page-b','buy-cow','download-exe'],
                        'allow' => true,
                        'roles' => ['@']
                    ],
                    [
                        'actions' => [ 'error'],
                        'allow' => true,
                    ]
                ]
            ]
        ];
    }
    /**
     * @param $action
     * @return bool
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action): bool
    {
        UserLog::add($action);
        return parent::beforeAction($action);
    }

    /**
     * @return string|Response
     */
    public function actionIndex()
    {
        if (AuthUser::userCan(Rbac::ROLE_ROOT)) {
            return $this->redirect(['user-log/index']);
        }
      return $this->render('index');
    }
    /**
     * @return string
     */
    public function actionPageA()
    {
          return $this->render('page-a');
    }

    /**
     * @return string
     */
    public function actionPageB()
    {
      return $this->render('page-b');
    }
    /**
     * @return Response
     */
    public function actionBuyCow()
    {
        Yii::$app->session->set('buy-cow',true);
        Yii::$app->session->setFlash('success', 'thankYou' );
        return $this->redirect(['site/index']);
    }
    /**
     * @return Response
     */
    public function actionDownloadExe()
    {
        $path = glob(Yii::getAlias('@app/runtime/test.exe'));
        return Yii::$app->response->sendFile($path[0]);
    }

}

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>
</div>

views/site/index.php
<?php


use app\components\AuthUser;
use yii\helpers\Url;


$this->title = 'Index';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row text-center">

    <div class="col-md-12">
        <h1>Hello <?= AuthUser::getUser()->username ?>!</h1>
    </div>
    <div class="col-md-6">
        <h1>
            <a href="<?= Url::toRoute(['site/page-a']) ?>">
                <button class="btn btn-primary btn-lg">
                    Page A
                </button>
            </a>
        </h1>
    </div>
    <div class="col-md-6">
        <h1>
            <a href="<?= Url::toRoute(['site/page-b']) ?>">
                <button class="btn btn-danger btn-lg">
                    Page B
                </button>
            </a>
        </h1>
    </div>


</div>

views/site/page-a.php
<?php


use app\components\AuthUser;
use yii\helpers\Url;


$this->title = 'Page A';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row text-center">
    <div class="col-md-12">
        <?php if (!Yii::$app->session->get('buy-cow')) { ?>
            <h1>
                <a href="<?= Url::toRoute(['site/buy-cow']) ?>">
                    <button class="btn btn-success btn-lg">
                        Buy a cow
                    </button>
                </a>
            </h1>
        <?php } ?>
    </div>
</div>

views/site/page-b.php
<?php


use app\components\AuthUser;
use yii\helpers\Url;


$this->title = 'Page B';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row text-center">
    <div class="col-md-12">
        <h1>
            <a href="<?= Url::toRoute(['site/download-exe']) ?>">
                <button class="btn btn-success btn-lg">
                    Download
                </button>
            </a>
        </h1>
    </div>
</div>